# Apache v2 license
#  Copyright (C) <2019> Intel Corporation
#
#  SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  inventory-data: 

networks:
  main-net:

services:  

  postgres-inventory:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
     main-net:
    logging:
      options: {max-file: '5', max-size: 100m}
    volumes:
      - "inventory-data:/var/lib/postgresql/data/"   

  inventory:    
    image: rsp/inventory-service:dev
    user: "2000:2000"
    ports:
      - "8080:8080"
    networks:      
      - main-net
    extra_hosts:
      - "edgex-core-data:172.17.0.1"
      - "edgex-support-logging:172.17.0.1"
      - "edgex-core-consul:172.17.0.1"
      - "edgex-core-command:172.17.0.1"
      - "edgex-support-notifications:172.17.0.1"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      options: {max-file: '5', max-size: 100m}
    environment:
      dbHost: "postgres-inventory"
      dbUser: "postgres"
      dbPass: ""
      dbPort: "5432"
      dbName: "postgres"
      dbSSLMode: "disable"
      loggingLevel: "debug"
      epcFilters: "[]"
      telemetryEndpoint: ""
      telemetryDataStoreName: "inventory-suite"
      responseLimit: 10000      
      port: "8080"      
      cloudConnectorUrl: "http://cloud-connector:8080"
      mappingSkuUrl: "http://product-data:8080/skus/"
      rfidAlertURL: "http://rfid-alert:8080"
      serviceName: "Inventory Service"
      ageOuts: "front:10,back:60"
      dailyInventoryPercentage: "0.01"
      probUnreadToRead: "0.20"
      probInStoreRead: "0.75"
      probExitError: "0.10"
      purgingDays: "90"
      serverReadTimeOutSeconds: 900
      serverWriteTimeOutSeconds: 900
      contextEventFilterProviderID: ""
      triggerRulesEndpoint: "/triggerrules"
      triggerRulesOnFixedTags: "true"
      newerHandheldHavePriority: "true"
      cloudConnectorApiGatewayEndpoint: "/callwebhook"
      rfidAlertMessageEndpoint: "/rfid-alert/alertmessage"
      eventDestination: ""
      eventDestinationAuthEndpoint: ""
      eventDestinationAuthType: ""
      eventDestinationClientID: ""
      eventDestinationClientSecret: ""
      dailyInventoryPercentageLabel: "daily_turn"
      probUnreadToReadLabel: "becoming_readable"
      probInStoreReadLabel: "being_read"
      probExitErrorLabel: "exit_error"
      endpointConnectionTimedOutSeconds: 15
      advancedShippingNoticeFacilityID: "UNDEFINED_FACILITY"
      rulesUrl: ""
      cloudConnectorRetrySeconds: 30
      proprietaryTagProductIdx: 2
      proprietaryTagBitBoundary: "8.44.44"
      tagURIAuthorityName: "example.com"
      tagURIAuthorityDate: "2019-01-01"
      dailyTurnMinimumDataPoints: 2
      dailyTurnHistoryMaximum: 25
      dailyTurnComputeUsingMedian: "false"
      useComputedDailyTurnInConfidence: "true"
      probPlugin: "false"   

