[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Inventory Service'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'
  
[MessageBus]
Type = 'zero'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = './logs/simple-filter-xml.log'

[Binding]
 Type="messagebus"
 SubscribeTopic=""
